/* ============================================================================
   program.js — The prescribed day-by-day sessions for all 5 phases, plus the
   Phase-5 sport variants. Transcribed from the KNCT Hybrid Apex System doc.
   Each day: { load, am:{focus,desc,items}, pm:{focus,desc,items} }.
   An `item` is { name, cat, sets, reps, load, rest, note } — `sets/reps` may be
   distances/minutes for conditioning. Loaded into the Log with one tap.
   ========================================================================== */

const PROGRAM = (() => {
  // exercise item helper
  const e = (name, cat, sets, reps, load, rest, note) => ({ name, cat, sets, reps, load, rest, note });

  const TEMPLATES = {
    /* ------------------------------- PHASE 1 ------------------------------- */
    1: {
      Mon: { load: 'HIGH',
        am: { focus: 'Speed Maintenance + Foundation', desc: 'Readiness gate (HRV + 3× CMJ). WU 15 min: 800m Z1 jog → leg swings → A/B-skips, dribbles 2×20m → 3× build-ups. Potentiation: 3× pogo hops ×10 (force plate, RSI>2.0).',
          items: [ e('Acceleration Wickets', 'speed', 6, '20 m', '95–98%', '3–4 min', '3-pt start, Freelap every rep — log 10m split + top speed. Total 120 m.') ] },
        pm: { focus: 'Strength (Olympic Bar + Belt Squat + Trap Bar)', desc: 'Top-set bar velocity (if VBT), session RPE.',
          items: [ e('Back Squat', 'strength', 5, 3, '82–85%', '3 min', '31X1 tempo, bar-speed focus'),
                   e('Trap-Bar Deadlift', 'strength', 4, 4, '80%', '3 min', 'Explosive concentric'),
                   e('Bench Press', 'strength', 5, 3, '80%', '2.5 min', 'Controlled'),
                   e('Belt-Squat March', 'strength', 3, '8 ea/leg', 'moderate', '90 s', 'Trunk stiffness'),
                   e('Nordic Curl', 'strength', 3, 6, 'BW', '2 min', 'Eccentric hamstring armor'),
                   e('Pallof / Anti-rotation', 'strength', 3, 12, '—', '60 s', 'Core') ] } },
      Tue: { load: 'LOW',
        am: { focus: 'Zone 2 (floor-builder)', desc: 'Resist speeding up — this is the aerobic-floor deposit.',
          items: [ e('Zone 2 Run', 'zone2', 1, '60–75 min', '~5:00–5:30/km · HR 72–80%', '—', 'Nasal-breathing test passes') ] },
        pm: { focus: 'Threshold (Stryd-anchored)', desc: 'Hold Stryd power in CP band ±3%. Threshold volume 24 min.',
          items: [ e('Threshold Run (LT2)', 'threshold', 4, '6 min', 'LT2 ~4:12–4:25/km · HR 86–90%', '90 s float', 'Bike/Row swap OK if legs flag') ] } },
      Wed: { load: 'HIGH',
        am: { focus: 'Extensive Tempo (aerobic-power bridge)', desc: 'Smooth, submaximal — capillary density + mechanics, no CNS cost. 1000 m volume.',
          items: [ e('Extensive Tempo', 'zone2', 2, '5×100 m', '70–75%', 'walk 100m / 3 min sets', 'Grass/track') ] },
        pm: { focus: 'Strength (Squat variation + posterior chain)', desc: 'Carry load, chin-up progression.',
          items: [ e('Front Squat', 'strength', 4, 4, '78%', '3 min', ''),
                   e('RDL', 'strength', 4, 6, '75%', '2.5 min', ''),
                   e('Weighted Chin-up', 'strength', 4, 5, '+load', '2 min', ''),
                   e('Jammer Press (explosive)', 'power', 4, '5 ea', 'moderate', '90 s', ''),
                   e('Heavy Farmer Carry', 'strength', 3, '40 m', 'heavy', '90 s', '') ] } },
      Thu: { load: 'LOW',
        am: { focus: 'Recovery Aerobic (off legs)', desc: 'Bank aerobic volume, low impact.',
          items: [ e('Zone 2 BikeErg', 'zone2', 1, '45–60 min', 'Z2', '—', 'or SkiErg') ] },
        pm: { focus: 'Mobility + Plyo Prep', desc: 'Grooving stiffness, not chasing height. Force plate every jump.',
          items: [ e('Ankle Pogos', 'plyo', 2, 10, 'BW', '—', 'RSI trend'),
                   e('Low Box Jump', 'plyo', 2, 5, 'step down', '—', '20 low-intensity contacts') ] } },
      Fri: { load: 'HIGH',
        am: { focus: 'Neural Primer + Power maint', desc: 'WU as Mon. Full recovery. Sprint ~120 m.',
          items: [ e('Hill Sprints', 'speed', 4, '30 m', '95%', 'full', 'Safer force output, low hamstring risk'),
                   e('Keiser Jump Squat', 'power', 2, 3, '25%', 'full', 'Power maintenance touch') ] },
        pm: { focus: 'Strength (whole-body, power-biased)', desc: 'Clean bar velocity, jump peak power (Keiser).',
          items: [ e('Power Clean (blocks)', 'power', 5, 3, '70–75%', '2.5 min', ''),
                   e('Box Squat', 'strength', 4, 3, '80%', '3 min', ''),
                   e('Incline Bench', 'strength', 4, 5, '75%', '2 min', ''),
                   e('Trap-Bar Jump', 'power', 4, 3, '20–30%', '2 min', ''),
                   e('Copenhagen Plank', 'iso', 3, '20 s ea', 'BW', '60 s', '') ] } },
      Sat: { load: 'MED-LOW',
        am: { focus: 'Long Aerobic', desc: 'Biggest single aerobic-floor deposit of the week. Last 10 min drift to top of Z2.',
          items: [ e('Zone 2 Run', 'zone2', 1, '75–90 min', 'Z2', '—', '') ] },
        pm: { focus: 'Strongman (structural robustness)', desc: 'Moderate loads, perfect posture — trunk stiffness + grip, no eccentric damage.',
          items: [ e('Yoke Carry', 'strength', 4, '20 m', 'moderate', '—', ''),
                   e('Sandbag Load-to-Shoulder', 'strength', 4, 5, 'moderate', '—', ''),
                   e('Heavy Sled Drag', 'strength', 4, '30 m', 'moderate', '—', ''),
                   e('Suitcase Carry', 'strength', 3, '30 m ea', 'moderate', '—', '') ] } },
      Sun: { load: 'RECOVERY',
        am: { focus: 'Recovery', desc: 'Optional 20–30 min Z1 shakeout or swim. Sauna 3×12 min. Mobility. Full nutrition + sleep priority. Weekly review: run diagnostic (Stryd CP + CMJ).', items: [] },
        pm: { focus: '—', desc: '', items: [] } },
    },

    /* ------------------------------- PHASE 2 ------------------------------- */
    2: {
      Mon: { load: 'HIGH',
        am: { focus: 'Acceleration', desc: 'WU 15 min. Full recovery 3–4 min. ~160 m.',
          items: [ e('Heavy Sled Push', 'speed', 6, '20 m', '75–90% BW', '3–4 min', 'Pure accel/force'),
                   e('Acceleration Sprint', 'speed', 2, '20 m', '95%', 'full', 'Unresisted') ] },
        pm: { focus: 'Max Strength Lower', desc: 'IMTP/Voltra peak force, top-set velocity — guard >0.30 m/s, stop if grinding.',
          items: [ e('Back Squat', 'strength', 6, 2, '90–93%', '4 min', ''),
                   e('Trap-Bar Deadlift', 'strength', 5, 2, '90%', '4 min', ''),
                   e('Voltra Isometric Hold', 'iso', 4, 'max 5 s', 'max', '3 min', 'Mid-thigh'),
                   e('Belt Squat (heavy)', 'strength', 4, 5, 'heavy', '2.5 min', ''),
                   e('Weighted Plank', 'iso', 3, '30 s', 'load', '90 s', '') ] } },
      Tue: { load: 'LOW',
        am: { focus: 'MED Aerobic', desc: 'Recovering from Monday near-max load — genuinely easy.',
          items: [ e('Zone 2 Run', 'zone2', 1, '45–55 min', 'HR 72–80%', '—', '') ] },
        pm: { focus: 'Optional Z1 + mobility', desc: '', items: [ e('Zone 1 Shakeout', 'zone2', 1, '20 min', 'Z1', '—', 'optional') ] } },
      Wed: { load: 'HIGH',
        am: { focus: 'Power Bridge (Keiser/Voltra)', desc: 'Ballistic, fresh, full recovery.',
          items: [ e('Keiser Jump Squat', 'power', 5, 3, '30%', 'full', 'Peak-watt focus'),
                   e('Voltra Explosive Press', 'power', 4, 4, 'power mode', 'full', '') ] },
        pm: { focus: 'Max Strength Upper + posterior', desc: 'Keiser peak watts, bench/chin loads.',
          items: [ e('Bench Press', 'strength', 5, 3, '88–90%', '3 min', ''),
                   e('Weighted Chin-up', 'strength', 5, 3, 'heavy', '3 min', ''),
                   e('Heavy RDL', 'strength', 4, 4, '85%', '3 min', ''),
                   e('Jammer Single-arm Press', 'power', 3, '5 ea', 'heavy', '90 s', ''),
                   e('Nordic Curl', 'strength', 3, 5, 'weighted if able', '2 min', '') ] } },
      Thu: { load: 'LOW',
        am: { focus: "MED Threshold (week's only one)", desc: 'Bike or run. ~24 min.',
          items: [ e('Threshold Run (LT2)', 'threshold', 3, '8 min', 'LT2', '2 min float', '') ] },
        pm: { focus: 'Mobility + 30 contacts low plyo', desc: 'Force-plate monitored.',
          items: [ e('Low Box Jump', 'plyo', 1, 30, 'BW', '—', 'Box jumps, pogos — low intensity') ] } },
      Fri: { load: 'HIGH',
        am: { focus: "Max-speed touch (week's only true speed)", desc: 'Protect top-end while strength dominates. ~200 m incl. run-ins.',
          items: [ e('Flying 20', 'speed', 4, '20 m', '100%', 'full 4–5 min', 'Freelap/OVR') ] },
        pm: { focus: 'Max Strength total-body', desc: 'Clean load, OVR flying-20 velocity.',
          items: [ e('Power Clean', 'power', 5, 2, '80–83%', '3 min', ''),
                   e('Front Squat', 'strength', 5, 3, '85%', '3 min', ''),
                   e('Push Press', 'power', 4, 3, '85%', '3 min', ''),
                   e('Trap-Bar Jump Shrug', 'power', 4, 3, '30%', '2 min', '') ] } },
      Sat: { load: 'MED',
        am: { focus: 'Heavy Strongman', desc: 'Force + robustness, low eccentric cost.',
          items: [ e('Yoke Carry', 'strength', 5, '20 m', 'heavy', '—', ''),
                   e('Heavy Sled Drag', 'strength', 5, '25 m', 'heavy', '—', ''),
                   e('Suitcase Carry', 'strength', 4, '30 m', 'heavy', '—', ''),
                   e('Stone-to-Platform', 'strength', 4, 3, 'heavy', '—', '') ] },
        pm: { focus: 'Z2 cross-train', desc: 'Hold the aerobic floor.',
          items: [ e('Zone 2 BikeErg', 'zone2', 1, '40–50 min', 'Z2', '—', 'bike/ski') ] } },
      Sun: { load: 'RECOVERY', am: { focus: 'Recovery', desc: 'Sauna/cold contrast, compression, mobility, sleep. Diagnostic: IMTP peak force + CMJ.', items: [] }, pm: { focus: '—', desc: '', items: [] } },
    },

    /* ------------------------------- PHASE 3 ------------------------------- */
    3: {
      Mon: { load: 'HIGH',
        am: { focus: 'Max Velocity + Ballistic Power', desc: 'Chase top-end while fresh. ~250 m.',
          items: [ e('Flying 30', 'speed', 4, '30 m', '100%', 'full 5–6 min', 'OVR every rep'),
                   e('Acceleration Sprint', 'speed', 2, '30 m', '95%', 'full', '') ] },
        pm: { focus: 'Ballistic Power (Keiser + Olympic)', desc: 'OVR flying-30, Keiser peak watts, CMJ.',
          items: [ e('Power Clean', 'power', 5, 3, '75–80%', '3 min', 'Max intent'),
                   e('Keiser Jump Squat', 'power', 5, 4, '30%', '2.5 min', 'Peak-watt PRs'),
                   e('Jump Squat (barbell)', 'power', 4, 3, '20–30%', '2 min', 'Velocity'),
                   e('Voltra Squat (velocity)', 'power', 4, 4, '~50%', '2 min', 'Bar-speed target') ] } },
      Tue: { load: 'LOW-MED',
        am: { focus: 'Reactive Plyometrics (60–80 contacts)', desc: 'Full recovery, quality only. RSI per contact, GCT.',
          items: [ e('Depth Jump', 'plyo', 4, 4, 'box 40–50 cm', 'full', 'RSI>2.2'),
                   e('Broad Jump', 'plyo', 4, 3, 'BW', 'full', ''),
                   e('Single-leg Bounds', 'plyo', 3, '20 m', 'BW', 'full', ''),
                   e('Reactive Hurdle Hops', 'plyo', 3, 6, 'BW', 'full', '') ] },
        pm: { focus: 'Z2', desc: '', items: [ e('Zone 2 Run', 'zone2', 1, '40 min', 'Z2', '—', 'easy') ] } },
      Wed: { load: 'HIGH',
        am: { focus: 'Speed-Endurance (400m development)', desc: 'Builds the speed reserve your 400 needs. ~450 m.',
          items: [ e('Flying 50', 'speed', 3, '50 m', '92–95%', 'full', ''),
                   e('150 m rep', 'speed', 2, '150 m', '92–95%', '6–8 min', '') ] },
        pm: { focus: 'Dynamic Effort Strength', desc: 'Bar velocity must stay >0.8 m/s on DE work.',
          items: [ e('Box Squat (dynamic)', 'power', 8, 2, '55–60%', '90 s', ''),
                   e('Trap-Bar Jump', 'power', 5, 3, '25%', '2 min', ''),
                   e('Explosive Bench (Jammer)', 'power', 6, 3, '55%', '90 s', ''),
                   e('Push Press', 'power', 4, 3, '65%', '2 min', '') ] } },
      Thu: { load: 'LOW',
        am: { focus: "Threshold MED (week's only one)", desc: '',
          items: [ e('Threshold Run (LT2)', 'threshold', 2, '10 min', 'LT2', '2 min float', '') ] },
        pm: { focus: 'Mobility + soft-tissue', desc: 'Legs fresh for Friday.', items: [] } },
      Fri: { load: 'HIGH',
        am: { focus: 'Accel-Power + Overspeed', desc: 'Full recovery throughout. ~180 m + assisted.',
          items: [ e('Voltra Resisted Sprint', 'speed', 4, '20 m', 'damper', 'full', 'resisted'),
                   e('Voltra/Band Overspeed', 'speed', 2, '20 m', 'assisted', 'full', 'overspeed'),
                   e('Light Sled Sprint', 'speed', 3, '20 m', '10–20% BW', 'full', 'max velocity') ] },
        pm: { focus: 'Reactive Strength + Olympic', desc: 'Overspeed velocity, complex jump height.',
          items: [ e('Hang Clean', 'power', 5, 2, '78%', '3 min', ''),
                   e('Depth Jump → Box Jump complex', 'plyo', 4, 3, 'BW', '2.5 min', ''),
                   e('Keiser Split-Squat (power)', 'power', 4, '4 ea', '35%', '2 min', ''),
                   e('Voltra Reactive (catch-release)', 'power', 3, 5, 'mod', '2 min', '') ] } },
      Sat: { load: 'MED',
        am: { focus: 'Dynamic Strongman', desc: 'Speed of movement > load.',
          items: [ e('Heavy Sled Push', 'power', 6, '20 m', 'fast', '—', 'fast sled push'),
                   e('Explosive Sandbag Load', 'power', 5, 3, 'explosive', '—', ''),
                   e('Med-ball Rotational Throw', 'power', 4, '5 ea', 'explosive', '—', ''),
                   e('Speed Farmer Carry', 'power', 4, '30 m', 'speed', '—', '') ] },
        pm: { focus: 'Z2', desc: 'Second aerobic maintenance dose.', items: [ e('Zone 2 Run', 'zone2', 1, '45–60 min', 'Z2', '—', 'easy') ] } },
      Sun: { load: 'RECOVERY', am: { focus: 'Recovery', desc: 'Full protocol. Diagnostic: Keiser peak watts + CMJ + Voltra F-V profile (shifting left = more force, right = more velocity — adjust load emphasis).', items: [] }, pm: { focus: '—', desc: '', items: [] } },
    },

    /* ------------------------------- PHASE 4 ------------------------------- */
    4: {
      Mon: { load: 'HIGH',
        am: { focus: 'Pure Max Velocity', desc: 'Highest-CNS day of the week. WU 25 min thorough. Stop the moment velocity drops >3% off best. ~350 m.',
          items: [ e('Flying 30', 'speed', 4, '30 m', '100%', 'full 6–8 min', 'OVR every rep'),
                   e('Flying 40', 'speed', 3, '40 m', '100%', 'full 6–8 min', '') ] },
        pm: { focus: 'Power maintenance (short)', desc: 'In-and-out.',
          items: [ e('Keiser Jump Squat', 'power', 3, 3, '30%', 'full', ''),
                   e('Ankle Pogos', 'plyo', 1, 20, 'BW', '—', 'quality contacts') ] } },
      Tue: { load: 'LOW',
        am: { focus: 'Recovery + Aerobic MED', desc: 'Genuinely easy. Speed phases live or die on recovery quality.',
          items: [ e('Zone 2 Run', 'zone2', 1, '40 min', 'Z2', '—', 'easy') ] },
        pm: { focus: 'Mobility + contrast therapy', desc: '', items: [] } },
      Wed: { load: 'HIGH',
        am: { focus: 'Speed-Endurance (400m engine)', desc: 'Specific 400m/football repeat-sprint quality. ~810 m.',
          items: [ e('150 m rep', 'speed', 3, '150 m', '93%', 'full 8 min', ''),
                   e('300 m rep', 'speed', 1, '300 m', '90%', 'full', ''),
                   e('Flying 30', 'speed', 2, '60 m', '100%', 'full', 'finish sharp') ] },
        pm: { focus: 'Strength maintenance', desc: '150/300 times, fade between reps.',
          items: [ e('Back Squat', 'strength', 3, 3, '82%', '3 min', ''),
                   e('Power Clean', 'power', 3, 2, '80%', '3 min', ''),
                   e('Bench Press', 'strength', 3, 3, '82%', '2.5 min', '') ] } },
      Thu: { load: 'MED',
        am: { focus: 'Max-quality Plyometrics (100–120 contacts)', desc: 'Force plate every contact — chase RSI PRs.',
          items: [ e('Depth Jump', 'plyo', 5, 4, 'box', 'full', ''),
                   e('Drop Jump', 'plyo', 4, 4, 'box', 'full', ''),
                   e('Single-leg Bounds', 'plyo', 4, '20 m', 'BW', 'full', ''),
                   e('Reactive Hurdle Hops', 'plyo', 4, 6, 'BW', 'full', '') ] },
        pm: { focus: "Threshold (only one)", desc: '',
          items: [ e('Threshold Run (LT2)', 'threshold', 2, '8 min', 'LT2', '2 min', '') ] } },
      Fri: { load: 'HIGH',
        am: { focus: 'Acceleration + Overspeed', desc: 'Full recovery throughout. ~200 m + assisted.',
          items: [ e('Block Starts', 'speed', 4, '20 m', '100%', 'full', ''),
                   e('Acceleration Sprint', 'speed', 3, '30 m', '100%', 'full', ''),
                   e('Voltra/Band Overspeed', 'speed', 3, '20 m', 'assisted', 'full', '') ] },
        pm: { focus: 'Reactive power maintenance', desc: 'Short.',
          items: [ e('Keiser Split-Squat (power)', 'power', 3, '3 ea', '35%', '2 min', ''),
                   e('Voltra Reactive (catch-release)', 'power', 3, 4, 'mod', '2 min', '') ] } },
      Sat: { load: 'MED',
        am: { focus: 'Extended Speed-Endurance', desc: '~500 m.',
          items: [ e('200 m rep', 'speed', 2, '200 m', '90%', 'full', ''),
                   e('Flying 50', 'speed', 2, '50 m', '100%', 'full', '') ] },
        pm: { focus: 'Z2', desc: 'Second aerobic dose.', items: [ e('Zone 2 Run', 'zone2', 1, '40–50 min', 'Z2', '—', 'easy') ] } },
      Sun: { load: 'RECOVERY', am: { focus: 'Recovery', desc: 'Full protocol. Diagnostic: OVR flying-30 + CMJ. Compare speed-decay to Phase 3 baseline.', items: [] }, pm: { focus: '—', desc: '', items: [] } },
    },

    /* --------------------- PHASE 5 (default = Track variant) --------------- */
    5: {
      Mon: { load: 'HIGH', am: { focus: 'Race-model reps', desc: 'e.g. 4×150m @ 400m goal pace. + CNS-priming lifts 3×2 @80%.',
          items: [ e('150 m rep', 'speed', 4, '150 m', 'goal pace', 'full', ''), e('Back Squat', 'strength', 3, 2, '80%', '3 min', 'CNS primer') ] },
        pm: { focus: '—', desc: '', items: [] } },
      Tue: { load: 'LOW', am: { focus: 'Z2', desc: '', items: [ e('Zone 2 Run', 'zone2', 1, '40 min', 'Z2', '—', '') ] }, pm: { focus: '—', desc: '', items: [] } },
      Wed: { load: 'HIGH', am: { focus: 'Speed-endurance modeling', desc: '300m + 200m + 100m descending, full recovery.',
          items: [ e('300 m rep', 'speed', 1, '300 m', 'race', 'full', ''), e('200 m rep', 'speed', 1, '200 m', 'race', 'full', ''), e('150 m rep', 'speed', 1, '100 m', 'race', 'full', '') ] }, pm: { focus: '—', desc: '', items: [] } },
      Thu: { load: 'LOW', am: { focus: 'Z2 + strides', desc: '', items: [ e('Zone 2 Run', 'zone2', 1, '30 min', 'Z2', '—', ''), e('Acceleration Sprint', 'speed', 6, '80 m', 'strides', 'walk-back', '') ] }, pm: { focus: '—', desc: '', items: [] } },
      Fri: { load: 'HIGH', am: { focus: 'Pure speed', desc: '30m ×3 + starts + power touch.',
          items: [ e('Acceleration Sprint', 'speed', 3, '30 m', '100%', 'full', ''), e('Block Starts', 'speed', 3, '20 m', '100%', 'full', '') ] }, pm: { focus: '—', desc: '', items: [] } },
      Sat: { load: 'MED', am: { focus: 'Time-trial or Z2', desc: 'TT/trial-rehearsal every 2nd week; Z2 otherwise.', items: [ e('Zone 2 Run', 'zone2', 1, '45 min', 'Z2', '—', '') ] }, pm: { focus: '—', desc: '', items: [] } },
      Sun: { load: 'RECOVERY', am: { focus: 'Recovery', desc: 'Full protocol. Diagnostic: full-effort trial component.', items: [] }, pm: { focus: '—', desc: '', items: [] } },
    },
  };

  /* Phase-5 sport variants — swap the whole week's content, skeleton holds. */
  const VARIANTS = {
    A: { name: 'Football (return May 2027)', emphasis: 'Acceleration, change-of-direction, repeat-sprint ability, robustness.',
      week: [ 'Mon HIGH: Accel 6×20m + COD ladder (5-10-5, T-drill) 6 reps full rest + strength maint (squat/clean 3×3 @78%)',
              'Tue LOW: Z2 40 min + mobility',
              'Wed HIGH: RSA — 6×40m every 30s ×2 sets (game-specific) + reactive plyos 40 contacts',
              'Thu LOW: Z2 35 min + threshold 2×6 min',
              'Fri HIGH: Max velocity 30m×4 + explosive strength (jump squat, push press)',
              'Sat MED: Small-sided game sim / conditioning games + strongman carry ×1',
              'Sun: Recovery' ],
      diagnostic: 'OVR 10m + flying-20 + RSA fade %' },
    B: { name: 'HYROX Pro (toward sub-57)', emphasis: 'Compromised running, station economy, threshold, hybrid transitions.',
      week: [ 'Mon HIGH: Threshold-run intervals 5×1km @ goal HYROX pace + strength maint (compound 3×4)',
              'Tue LOW: Z2 60 min + SkiErg/Row Z2 technique',
              'Wed HIGH: Station sim — RowErg 1km → 100m sled push → wall balls → run 1km, ×3 rounds @ race effort (transitions timed)',
              'Thu LOW: Z2 45 min + mobility',
              'Fri HIGH: Compromised-running intervals: run 400m → 50m lunge → run 400m, ×4 + power maint',
              'Sat MED: Half-HYROX simulation (4 stations + runs) OR long Z2 75 min',
              'Sun: Recovery' ],
      diagnostic: '1km compromised-run split + station benchmarks (sled, ski, row, burpee-broad-jump)' },
    C: { name: 'Track (100/200/400 or mile)', emphasis: 'Race modeling, speed reserve, pacing.',
      week: [ 'Mon HIGH: Race-model reps at goal pace (e.g. 4×150m @ 400m goal) + CNS-priming lifts 3×2 @80%',
              'Tue LOW: Z2 40 min',
              'Wed HIGH: Speed-endurance modeling (300+200+100 descending) full recovery',
              'Thu LOW: Z2 + strides 6×80m',
              'Fri HIGH: Pure speed 30m×3 + starts + power touch',
              'Sat: Time-trial or trial-rehearsal every 2nd week; Z2 otherwise',
              'Sun: Recovery' ],
      diagnostic: 'Full-effort trial component' },
  };

  // Look up today's prescribed session for a phase id + weekday abbrev.
  function forDay(phaseId, dayAbbr) {
    const ph = TEMPLATES[phaseId] || TEMPLATES[1];
    return ph[dayAbbr] || null;
  }

  return { TEMPLATES, VARIANTS, forDay };
})();
